stages:
  download:
    cmd: bash stages/00_download.sh
    deps:
    - stages/00_download.sh
    outs:
      - download/
  process:
    cmd: |-
      Rscript stages/01_process.R && python3 stages/02_process_embl.py
    deps:
    - download/
    - stages/01_process.R
    - stages/02_process_embl.py
    outs:
      - brick/
